name: Deploy DymensionHub
on:
  workflow_dispatch:
    inputs:
      validators:
        description: 'Number of validators in private dymensionhub testnet'
        required: true
        default: '1'
        type: choice
        options:
          - 2
          - 4
      rollaps:
        description: 'Number of rollaps to deploy'
        required: false
        default: '1'
        type: choice
        options:
          - 1
          - 2
          - 4
          - 8

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      ROLLAPS: ${{ github.event.inputs.rollaps || 1 }}
      VALIDATORS: ${{ github.event.inputs.validators || 1 }}
      DATA_USER: ${{ github.actor }}
    permissions:
      id-token: write
      contents: read
    steps:

# REFERENCE: https://github.com/aws-actions/configure-aws-credentials#overview
# ENHANCEMENT: SLC can be further tightened with the use of two separate OICD providers;
# one for mainnet and one for testnet
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::044425962075:role/dybench-deploy-slc
        role-duration-seconds: 900
        aws-region: us-west-2 

    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false    

    - name: Spin chain validators
      run: |
        ./.github/scripts/deploy_dyhub.sh ${{ env.VALIDATORS }}

    - name: Sleep for 3 minutes
      run: sleep 180s
      shell: bash
      
    - name: Bootstrap network
      run: |
        ./.github/scripts/bootstrap_network.sh ${{ env.VALIDATORS }}
    
    - name: Deploy RollApps
      run: |
        ./.github/scripts/deploy_rollApps.sh ${{ env.ROLLAPS }}  

# This is dummy code:        
    - name: Instantiate Redis and configure schema
      run: |
        ./.github/scripts/deploy_redis.sh

# These are dummy steps :
#
# Based on tx type selection, the workflow sends a workflow_dispatch trigger that launches 
# a separate wf for each type, for example dybench_workload1.yaml


# when all workloads are finished, we release all computes besides redis:
    - name: Terminate Computes
      run: |
        ./.github/scripts/terminate_computes.sh
      
    - name: Calculate bench results
      run: |
        ./.github/scripts/calculate.sh
    
    - name: Upload Bench results Artifact
      run: |
        pass

    - name: Terminate Redis
      run: |
        pass

