name: Deploy DymensionHub
on:
  workflow_dispatch:
    inputs:
      validators:
        description: 'Number of validators in private dymensionhub testnet'
        required: true
        default: '1'
        type: choice
        options:
          - 2
          - 4
      rollaps:
        description: 'Number of rollaps to deploy'
        required: false
        default: '1'
        type: choice
        options:
          - 1
          - 2
          - 4
          - 8

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      ROLLAPS: ${{ github.event.inputs.rollaps || 1 }}
      VALIDATORS: ${{ github.event.inputs.validators || 1 }}
      DATA_USER: ${{ github.actor }}
    permissions:
      id-token: write
      contents: read
    steps:

# REFERENCE: https://github.com/aws-actions/configure-aws-credentials#overview
# ENHANCEMENT: SLC can be further tightened with the use of two separate OICD providers;
# one for mainnet and one for testnet
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::044425962075:role/dybench-deploy-slc
        role-duration-seconds: 900
        aws-region: us-west-2 

    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false    

    - name: Spin chain validators
      run: |
        ./.github/scripts/deploy_dyhub.sh ${{ env.VALIDATORS }}

    - name: Sleep for 3 minutes
      run: sleep 180s
      shell: bash
      
    - name: Bootstrap network
      run: |
        ./.github/scripts/bootstrap_network.sh ${{ env.VALIDATORS }}
    
    - name: Deploy RollApps
      run: |
        ./.github/scripts/deploy_rollApps.sh ${{ env.ROLLAPS }}  

